### ISSUE TITLE
Help needed to upload file using API

### ISSUE THREAD

**Issue by rogeriotaques** [humantech/zoho-recruit-api#3]
Not been able to upload files. I'm always getting an error message that says: 

```
Fatal error</b>:  Uncaught exception 'Humantech\Zoho\Recruit\Api\Client\HttpApiException' with message 'Problem occured while processing the request' in .../vendor/humantech/zoho-recruit-api/src/Formatter/AbstractFormatter.php:128
```

**Comment by jpcercal** [comment]
Hey @rogeriotaques, first of all, my apologies for the delay in getting back to you. =/

Well, I'm not a core member of this project anymore since I leave this company a few years ago. However, you can try to be in touch with @rluders, @tewald or @basask to try to solve your issue. If I need to support you guys with something just let me know.

**Comment by rogeriotaques** [comment]
Hi, @jpcercal! Thanks for letting me know. It was a few time ago already, but I have fixed it somehow. :) Cheers.

**Comment by rluders** [comment]
Hi. So, I think that this library is deprecated.

**Comment by rogeriotaques** [comment]
Thanks for answering @rluders. Any replacement for that library or it was just discontinued?

**Comment by rluders** [comment]
@rogeriotaques I think this will be just discontinued, but I'm not at the development team anymore.

**Comment by rogeriotaques** [comment]
@rluders thanks for the feedback! No worries.
